### ISSUE TITLE
osxutils is for some reason slowing down localhost web server

### ISSUE THREAD

**Issue by geigel** [neoneye/osxutils#1]
Via Homebrew I have installed an Apache server with PHP and accessible via http://localhost/. I needed the ability to manipulate file comments so I installed osxutils via Homebrew too. Once osxutils was installed, however, my localhost web server absolutely crawled with pages loading very slowly. The moment I uninstalled osxutils things went back to normal loading lighting fast. I installed osxutils again and again the web server crawled. While it was trying to load a page I deleted osxutils and then a split second later my page loaded.

This is happening without me even having used or taken advantage of osxutils features. Just the existence of it installed cause the web server to effectively crash.

Just reporting in case anyone else ran into this and if there's something simple that you can think of that might be causing it.

**Comment by neoneye** [comment]
Sorry, my repo is a 10 year old fork of Sveinbjorn Thordarson's `osxutils`.

The most uptodate fork of osxutils seems to be
https://github.com/specious/osxutils
which is referenced in the homebrew formula
https://formulae.brew.sh/formula/osxutils
